server:
  port: 8002

spring:
  application:
    name: service-oss
  profiles:
    active: dev

#阿里云 OSS
aliyun:
  oss:
    file:
      endpoint: oss-cn-beijing.aliyuncs.com
      keyid: LTAI5tExGxC3H6sv265UQFfG
      keysecret: y4n07kFlBj8WVQF6OvK3sndnhSLLyK
      bucketname: gili-edu-lch

